### ISSUE TITLE
return null when mode.array: DIFF_MODES.REFERENCE

### ISSUE THREAD

**Issue by hchoong** [netilon/differify#36]
From this example, https://github.com/netilon/differify#with-the-option-string-or-reference

```
  const differify = new Differify({
    compareArraysInOrder: false,
    mode: {
      object: DIFF_MODES.DIFF,
      array: DIFF_MODES.REFERENCE
    }
  });

const testA = [1,2];
const testB = [1,3];

const result = differify.compare(testA, testB);
```

result:
```
{
	"_": null,
	"status": "MODIFIED",
	"changes": 1
}
```
Why the result has no original or current value (no diff info)? This null return resulted in `differify.applyRightChanges(diff, true);` also be null.

**Comment by hchoong** [comment]
should these two lines, https://github.com/netilon/differify/blob/master/src/comparator-selector.ts#L90 and https://github.com/netilon/differify/blob/master/src/comparator-selector.ts#L94 be 
```
return buildDiff(a, b, pDiff.status, pDiff.changes);
```

**Comment by fabian-orue** [comment]
Hi @hchoong, the original / current values are only available using `DIFF_MODES.DIFF`. In your example, I can see that you are using `array: DIFF_MODES.REFERENCE` and that will do a reference check and because of that there will no "extra" information to show in original / current properties (because there is no deep checking ). But maybe i could add the entire input (elements to be compared) as original and current values to be used as inputs for methods you mentioned such as `applyRightChanges`. I will do that change soon. 

Thanks for the improvement!

**Comment by hchoong** [comment]
@fabian-orue thank for the reply. I have the changes in pull request. We are looking to have the fix for both `array: REFERENCE` and `array: STRING`

https://github.com/netilon/differify/pull/37

**Comment by fabian-orue** [comment]
Hi @hchoong, I rejected your pull request, because this change envolved some other changes to have in mind (combinations of different DIFF MODES for different data types). I have done the changes and a new version was released (the major has changed) because of the breaking changes in the output of the diff result for the specific configurations. In addition, i have added tests to cover the changed functionality, updated the documentation and added a very simple changelog based on the git commits. 

Thank you for your suggestions. 

Regards.
